services:
  - type: web
    name: entertainmenthub
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn FILMS.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: entertainmenthub-l0yx.onrender.com
      - key: CONTENT_ADMIN_USERNAME
        value: admin
      - key: DATABASE_URL
        sync: false
