# Generated by Django 5.2.13 on 2026-09-09 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0007_country'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='movie',
            new_name='WEBSITE_mov_is_publ_de4ba4_idx',
            old_name='WEBSITE_movi_is_publ_8c1b10_idx',
        ),
        migrations.RenameIndex(
            model_name='moviecomment',
            new_name='WEBSITE_mov_movie_i_5fba18_idx',
            old_name='WEBSITE_movieco_movie_i_1d8f9c_idx',
        ),
        migrations.RenameIndex(
            model_name='movielike',
            new_name='WEBSITE_mov_movie_i_f2f078_idx',
            old_name='WEBSITE_moveli_movie_i_6d9a6a_idx',
        ),
        migrations.RenameIndex(
            model_name='short',
            new_name='WEBSITE_sho_status_d65d9a_idx',
            old_name='WEBSITE_shor_status_7e5b13_idx',
        ),
    ]
